Normalize date formatting and domain checking
Chatterino/api pull request #105
Opened 2021-03-21 16:15 UTC by pajlada

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

2021-03-21 16:19 UTC, zneix requested changes

2021-03-21 16:19 UTC, zneix commented on CHANGELOG.md
> +- Twitter resolver timestamp date format changed from `Jan 2 2006` to `02 Jan 2006`
Include PR number in the changelog entry
```suggestion
- Twitter resolver timestamp date format changed from `Jan 2 2006` to `02 Jan 2006` (#105)
```

2021-03-21 16:45 UTC, pajlada commented
@zneix please take a look at this LurkMode

I will be running this locally for a while to ensure it works as expected since we don't have many tests that would cover this

2021-03-21 18:50 UTC, zneix reviewed
Code seems good to me, however I will try this PR out on my instance of the API and see how it works.

2021-03-28 13:56 UTC, pajlada commented
![image](https://user-images.githubusercontent.com/962989/112754826-2f0fac00-8fde-11eb-86e0-e17ccee324eb.png)

2021-03-28 14:02 UTC, merged