fix: Original quality Twitter profile pictures.
Chatterino/api pull request #131
Opened 2021-04-22 15:39 UTC by KararTY

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

Note: **I've not tested this fix.**

As per @leon-richardt's link on issue #130, Twitter recommends modifying the received URL, to get a higher quality profile picture. This also works for users who haven't set a profile picture.

Closes #130

2021-04-22 15:44 UTC, leon-richardt commented
I think I would prefer doing this in `api.go` where the `TwitterUserApiResponse` is built

2021-04-22 15:53 UTC, KararTY commented
> I think I would prefer doing this in `api.go` where the `TwitterUserApiResponse` is built

Good call!

2021-04-22 15:55 UTC, leon-richardt requested changes

2021-04-22 15:55 UTC, leon-richardt commented on internal/resolvers/twitter/api.go
> +	// Do modifications to response
Either drop this comment or explain why the modification is necessary (could also link to the API documentation here)

2021-04-22 16:40 UTC, zneix commented
For some reason this keeps returning 500 
![](https://cdn.zneix.eu/GJ9NqAE.png)

2021-04-22 17:38 UTC, zneix approved these changes
Works as intended :+1: 

![sorry leon and karar, my setup was lidl](https://cdn.zneix.eu/w9O5CLi.gif)

2021-04-24 11:52 UTC, pajlada approved these changes
Tested and LGTM :+1:

2021-04-24 11:56 UTC, merged