Add Chatterino API Privacy Policy and Terms of Service
Chatterino/api pull request #253
Opened 2021-12-19 17:04 UTC by pajlada

- Add privacy policy and terms of service
- stop gitignore from ignoring everything in the cmd/api directory

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

2021-12-19 17:29 UTC, pajlada commented
@Felanbird Could you do an English check on the text?

2021-12-19 17:33 UTC, pajlada commented
pretty links can be found here:
https://pajbot.com/static/chatterino-api-tos.html
https://pajbot.com/static/chatterino-api-pp.html

2021-12-19 17:39 UTC, zneix commented on cmd/api/legal.go
> +	If you have any questions about this terms of service, you can <a href="https://github.com/Chatterino/api/issues/new">contact us</a>.
```suggestion
	If you have any questions about these Terms of Service, you can <a href="https://github.com/Chatterino/api/issues/new">contact us</a>.
```
or
```suggestion
	If you have any questions about our Terms of Service, you can <a href="https://github.com/Chatterino/api/issues/new">contact us</a>.
```

2021-12-19 17:47 UTC, Felanbird commented
`these` is probably better, it seems to be common to see both `this` and `these` terms of service...

2021-12-19 17:52 UTC, Felanbird requested changes

2021-12-19 17:52 UTC, Felanbird commented on cmd/api/legal.go
> +    Using the Chatterino API from the Chatterino Client is perfectly fine.
```suggestion
    Usage of the Chatterino API from the Chatterino Client is perfectly fine.
```
The original is perfectly fine, I just feel like the word `Usage` is very often used in this sort of thing

2021-12-19 17:52 UTC, Felanbird commented on cmd/api/legal.go
> +    <li>YouTube Videos and Channels through the YouTube Data API. Google's Privacy policy can be found here: <a href="https://policies.google.com/privacy">https://policies.google.com/privacy</a>. Not
```suggestion
    <li>YouTube Videos and Channels through the YouTube Data API. Google's Privacy Policy can be found here: <a href="https://policies.google.com/privacy">https://policies.google.com/privacy</a>. Note that no data is forwarded about you the user to the YouTube Data API.</li>
```

2021-12-19 17:52 UTC, Felanbird commented on cmd/api/legal.go
> +	If you have any questions about this privacy policy, you can <a href="https://github.com/Chatterino/api/issues/new">contact us</a>.
```suggestion
	If you have any questions about this Privacy Policy, you can <a href="https://github.com/Chatterino/api/issues/new">contact us</a>.
```

2021-12-19 23:39 UTC, Felanbird approved these changes

2021-12-23 18:21 UTC, zneix approved these changes

2021-12-25 13:18 UTC, merged