Use govips instead of lilliput
Chatterino/api pull request #312
Opened 2022-04-23 22:10 UTC by KararTY

Preview: https://streamable.com/0lu2pe

There's a few pain-points with govips (You have to build from source to get the latest and greatest - And it's not very straightforward) but it solves several issues that lilliput has:

* Animated WebP is supported. (See video)
* The output parameters actually work, which means one can reduce the output size considerably. (See video)
* We can do custom outputs based on the input, which also means custom quality etc. (In video everything is exported as WebP with quality at 10%)

But, I'm just danking around. Consider this a proof-of-concept, maybe someone else can look into govips / vips and see how to implement this.

2022-10-17 22:43 UTC, KararTY commented
I've been unable to get avif to work, on Windows by using the suffix -all binary distribution, or on WSL/Ubuntu by rebuilding libvips with libheif-dev.

Should maybe still support 7TV previews? Their non-suffix/non-file-format-ending version uses animated WebP which works with out of the box libvips on Ubuntu & Windows -static/-all distributions.

2022-10-18 07:59 UTC, leon-richardt commented
Should we maybe continue supporting the `enable-lilliput` parameter as an alias for `enable-animated-thumbnails` and print a deprecation warning when it's used? That way, this needn't be a breaking change.

2022-10-18 09:35 UTC, leon-richardt commented
> > Should we maybe continue supporting the `enable-lilliput` parameter as an alias for `enable-animated-thumbnails` and print a deprecation warning when it's used? That way, this needn't be a breaking change.
> 
> I was thinking about making that change a separate PR, but since the switch to libvips is a breaking change and that feature hasn't landed in a released version of chatterino/api I thought it wouldn't really matter how many breaking changes you shove in. :joy: :ok_hand:

Good point. I agree now that the `enable-lilliput` should not be an alias.

> 
> I like the idea of a deprecation notice, however.
> 

I would even argue that we should error out if the `enable-lilliput` parameter is used in the config since ignoring it could lead to unexpected behavior. For example, suppose the following scenario:
1. User has `enable-lilliput: false` in his config to disable the generation of animated thumbnails.
2. User upgrades their version to the new release which uses `enable-animated-thumbnails` instead.
3. Since `enable-animated-thumbnails` is `true` by default, animated thumbnails will now be generated even though the user has not made any changes to their config.

By erroring out with a descriptive message when the old parameter is detected, we can make sure users are not running into unexpected behavior when upgrading.

2022-10-20 11:00 UTC, leon-richardt reviewed
Other than changing the logging method to what's used elsewhere, I think this looks good :+1:

2022-10-20 11:00 UTC, leon-richardt commented on pkg/thumbnail/thumbnail.go
> +		fmt.Println(err)
Should use a logger derived with logger.FromContext() here. (Requires passing down the request context to BuildAnimatedThumbnail() but this is considered good practice anyway.)

2022-10-20 11:00 UTC, leon-richardt commented on pkg/thumbnail/thumbnail.go
> +	}
Should use a logger derived with logger.FromContext() here. (Requires passing down the request context to BuildAnimatedThumbnail() but this is considered good practice anyway.)

2022-10-20 11:00 UTC, leon-richardt commented on pkg/thumbnail/thumbnail.go
> +	}
Should use a logger derived with logger.FromContext() here. (Requires passing down the request context to BuildAnimatedThumbnail() but this is considered good practice anyway.)

2022-10-20 14:01 UTC, KararTY commented
> Other than changing the logging method to what's used elsewhere, I think this looks good 👍

Wouldn't this be a change for BuildStaticThumbnail() too? Maybe best if done in separate PR?

2022-10-20 14:04 UTC, leon-richardt commented
> > Other than changing the logging method to what's used elsewhere, I think this looks good +1
> 
> Wouldn't this be a change for BuildStaticThumbnail() too? If so, maybe best if done in separate PR?

Yes, I should have done that in `BuildStaticThumbnail()` as well. But I still think that **this** PR should include the change for `BuildAnimatedthumbnail()`

2022-10-29 10:01 UTC, pajlada requested changes

2022-10-29 10:01 UTC, pajlada commented on pkg/thumbnail/thumbnail.go
> +		return []byte{}, err
user friendly error

2022-10-29 10:01 UTC, pajlada commented on pkg/thumbnail/thumbnail.go
> +		return []byte{}, err
user friendly error

2022-10-29 10:01 UTC, pajlada commented on pkg/thumbnail/thumbnail.go
> +	// We export to WebP by default to save on bandwidth and cache storage.
No need for a comment here, no justifications needed

2022-10-29 11:14 UTC, pajlada approved these changes

2022-10-29 12:49 UTC, merged