implement imgur resolving, a lot of nil pointer references, can't qui…
Chatterino/api pull request #365
Opened 2022-10-03 10:56 UTC by gempir

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

Allow imgur.io to urls to be resolved as per #361 I still can't fully test this because I keep getting nil pointers. First with the logger now in the postgres pool somewhere, very annoying to debug.

2022-10-18 10:20 UTC, leon-richardt commented on internal/resolvers/imgur/resolver.go
> +	return ctx, false
This seems to be causing the error you're running into. The `Context` returned by the method is later used in `internal/resolvers/default/link_resolver.go` and will cause an error if it's `nil`. The error can be resolved with this change:

```suggestion
	for _, domain := range VALID_IMGUR_DOMAINS {
		result := utils.IsSubdomainOf(url, domain)
		if result {
			return ctx, result
		}

		result = utils.IsDomain(url, domain)
		if result {
			return ctx, result
		}
	}

	return ctx, false
```

---

However, even after making this change, imgur.io domains will not be resolved correctly. [It seems that `koffeinsource/go-imgur` does not support that domain yet](https://github.com/koffeinsource/go-imgur/blob/master/fromURL.go#L20-L44).

2022-10-18 11:20 UTC, leon-richardt commented on internal/resolvers/imgur/resolver.go
> +	return ctx, false
Small update: I have created https://github.com/koffeinsource/go-imgur/pull/16 at the upstream repository to raise awareness.

2022-10-20 09:22 UTC, leon-richardt commented
https://github.com/koffeinsource/go-imgur/pull/16 has been merged upstream and is included in the `v0.4.1` release.
@gempir, if you rebase your branch on `master` and bump the version in `go.mod`, it should Just Work:tm:.

2022-10-22 10:23 UTC, pajlada requested changes

2022-10-22 10:23 UTC, pajlada commented on CHANGELOG.md
> +- Dev: Resolve imgur.io links (#365)
```suggestion
- Dev: Resolve imgur.io links. (#365)
```

2022-10-22 10:23 UTC, pajlada approved these changes

2022-10-22 10:34 UTC, merged