Prettier Formatting for Twitter Tooltips
Chatterino/api pull request #40
Opened 2020-09-06 12:43 UTC by leon-richardt

As suggested by @KararTY in Twitch chat, this PR adds `<style>` tags to the rich Twitter tooltips introduced in #38.
This leads to "better" behavior on some Tweets (e.g. https://twitter.com/QuoteRed/status/312215975040778240) but could potentially be annoying for other Tweets (e.g. https://twitter.com/ianchaffee/status/311940617217392640). I do not believe this is not much of a problem though since you can "just" hover off of a Tweet that produces a large tooltip.

Additionally, we now truncate numbers larger than one million to one decimal place (for followers, likes, and retweets). This also mimics Twitter's behavior.

2020-09-06 12:47 UTC, KararTY approved these changes

2020-09-10 15:51 UTC, leon-richardt commented
Depends on how well I can get screenshots working on sway. 😛

2020-09-11 11:22 UTC, leon-richardt commented
@RAnders00 I updated the original post to include tooltip screenshots of the mentioned Tweets.

2020-09-12 12:12 UTC, pajlada requested changes

2020-09-12 12:12 UTC, pajlada commented on link_resolver_twitter.go
> +}
please move this into utils.go

2020-09-12 12:20 UTC, pajlada approved these changes

2020-09-12 12:20 UTC, merged