Use maintained version of prometheus middleware
Chatterino/api pull request #425
Opened 2023-01-29 11:08 UTC by M4tthewDE

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

Uses maintained version of prometheus middleware. Only creates metrics for the patterns
that the router matches.

2023-01-29 11:39 UTC, M4tthewDE commented
Not sure how to handle the Changelog entry in this case.

2023-01-29 12:53 UTC, pajlada requested changes

2023-01-29 12:53 UTC, pajlada commented on CHANGELOG.md
> +- Dev: Only create prometheus metrics for router patterns. (#425)
Make only one changelog entry, treat this PR as if it's the first that handles router prometheus metrics

2023-01-29 12:53 UTC, pajlada commented on cmd/api/main.go
> +	chiprometheus "github.com/ppaanngggg/chi-prometheus"
Use the well-maintained fork instead
https://github.com/nathan-jones/chi-prometheus
His go.mod file is much more managed & doesn't reference other chi-prometheus forks (WAYTOODANK)

2023-02-04 11:40 UTC, pajlada approved these changes

2023-02-04 11:47 UTC, merged