feat: Livestreamfails resolver.
Chatterino/api pull request #98
Opened 2021-03-15 09:42 UTC by KararTY

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

Added a Livestreamfails resolver for livestreamfails links:

https://livestreamfails.com/clip/109643 
![image](https://user-images.githubusercontent.com/13697809/111133486-e1755700-857a-11eb-97dc-5bb0e99d9946.png)

NSFW marked clips will not show thumbnail:
https://livestreamfails.com/clip/109660
![image](https://user-images.githubusercontent.com/13697809/111133577-f81bae00-857a-11eb-9dc4-5a219e0acad2.png)

2021-03-15 10:33 UTC, KararTY commented
On second note, I'm putting this pr into draft because lsf might change their CDN again:
![image](https://user-images.githubusercontent.com/13697809/111140046-2c469d00-8582-11eb-9fa9-15184c5da110.png)

2021-03-18 18:24 UTC, zneix requested changes
Looks good to me

2021-03-18 18:24 UTC, zneix commented on internal/resolvers/livestreamfails/model.go
> +}
I believe that some fields of this struct may be unnecessary, you could try to remove some.

2021-03-19 16:40 UTC, zneix approved these changes

2021-03-20 12:01 UTC, pajlada requested changes

2021-03-20 12:47 UTC, pajlada commented on internal/resolvers/livestreamfails/load.go
> +		StreamerName: clipData.Streamer.Label,
Nevermind, not necessary as you use the `html/template` package instead of `text/template`

2021-03-20 12:47 UTC, pajlada approved these changes

2021-03-20 12:48 UTC, merged